[package]
name = 'cedra_names_distribute'
version = '1.0.0'

[addresses]
cedra_names = "_"
cedra_names_admin = "_"
cedra_names_funds = "_"
router_signer = "_"

[dependencies.cedra_names]
local = "../core"

[dependencies.CedraToken]
git = 'https://github.com/cedra-labs/cedra-framework.git'
rev = 'testnet'
subdir = 'cedra-token'
