[package]
name = 'router'
version = '1.0.0'

[addresses]
cedra_names = "_"
cedra_names_v2_1 = "_"
cedra_names_admin = "_"
cedra_names_funds = "_"
router_signer = "_"

[dependencies.cedra_names]
local = "../core"

[dependencies.cedra_names_v2_1]
local = "../core_v2"

[dependencies.CedraFramework]
git = 'https://github.com/cedra-labs/cedra-network.git'
rev = 'devnet'
subdir = 'cedra-move/framework/cedra-framework'

[dependencies.CedraToken]
git = 'https://github.com/cedra-labs/cedra-network.git'
rev = 'devnet'
subdir = 'cedra-move/framework/cedra-token'

[dependencies.CedraTokenObjects]
git = 'https://github.com/cedra-labs/cedra-network.git'
rev = 'devnet'
subdir = 'cedra-move/framework/cedra-token-objects'
