[package]
name = 'cedra_names_transfer'
version = '1.0.0'

[addresses]
cedra_names = "_"
cedra_names_admin = "_"
cedra_names_funds = "_"
router_signer = "_"

[dev-addresses]
cedra_names = "0x5555000"
cedra_names_admin = "0x5555002"
cedra_names_funds = "0x5555003"
router_signer = "0x5555004"

[dependencies.cedra_names]
local = "../core"
