[package]
name = 'cedra_names_v2_1'
version = '1.0.0'

[addresses]
cedra_names_v2_1 = "_"
cedra_names_admin = "_"
cedra_names_funds = "_"
router_signer = "_"

[dependencies.CedraFramework]
git = 'https://github.com/cedra-labs/cedra-framework.git'
rev = 'main'
subdir = 'cedra-framework'

[dependencies.CedraToken]
git = 'https://github.com/cedra-labs/cedra-framework.git'
rev = 'main'
subdir = 'cedra-token'

[dependencies.CedraTokenObjects]
git = 'https://github.com/cedra-labs/cedra-framework.git'
rev = 'main'
subdir = 'cedra-token-objects'
