name: "Move Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - testnet
      - mainnet

jobs:
  move-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cedra CLI
        run: |
          if ! command -v cedra >/dev/null 2>&1; then
            sudo add-apt-repository -y ppa:cedra-network/deps
            sudo apt-get update -y
            sudo apt-get install -y cedra-cli
          fi
          cedra --version
      - uses: actions/checkout@v4
      - name: Runs move tests.
        run: ./sh_scripts/move_tests.sh
